### ISSUE TITLE
Agenda werkgroepen

### ISSUE THREAD

**Issue by MPParsley** [Informatievlaanderen/OSLOthema-ldes#1]
Is het mogelijk om hier de agenda te documenteren voor de verschillende werkgroepen?

**Comment by ArneVanDerStuyft** [comment]
Aangezien we de specificatie iteratief zullen opbouwen tijdens de thematische werkgroepen zijn er nog geen agenda's van de sessies beschikbaar. Wel zullen we in de eerste thematische werkgroep de input van de business werkgroep bespreken. Vervolgens zullen we in de tweede thematische werkgroep verder werken op de (verwerkte) output van de eerste thematische werkgroep, etc. Naargelang de voorbereiding van een werksessie vordert, en de agenda ervan vorm begint te krijgen, zullen wij deze zeker delen. Mocht u willen meewerken aan dit traject, gelieve dan in te schrijven voor elk van de thematische werkgroepen. Dit kan op de volgende pagina: https://overheid.vlaanderen.be/opleiding/oslo-ldes
