### ISSUE TITLE
Logische delete vs fysieke delete

### ISSUE THREAD

**Issue by MPParsley** [Informatievlaanderen/OSLOthema-ldes#3]
Niet alle systemen voorzien een logische delete (status vlag). Wat is de aangewezen manier om om te gaan met het publiceren van fysieke deletes in een bron (e.g. een retentie policy of alsnog een status voorzien oid.)?

**Comment by pietercolpaert** [comment]
Ik zou inderdaad beide opties als mogelijkheden zien: ofwel een retention policy definiëren indien mogelijk, of alsnog een status voorzien voor verwijderde objecten.

**Comment by pietercolpaert** [comment]
Meer volledig antwoord:

Een fysieke delete is niet echt een delete: het is gewoon niet meer beschikbaar on disk maar is conceptueel wel nog deel van de LDES. Hiervoor kan je op je `tree:ViewDescription` een retention policy definiëren om duidelijk te maken dat de server bepaalde members niet meer zal bijhouden.

Een logische delete is een conceptuele verwijdering waarbij we willen dat een afnemer die member niet meer zal tonen in z’n interface. Verschillende opties:
 1. Je hebt een domeinmodel waarbij je “versionOf” gebruikt om versies van objecten te ondersteunen. In dit geval moet je een nieuwe versie van het object publiceren waarbij duidelijk is dat dit object niet meer actief is. Zoals bijvoorbeeld: een _afgeschafte_ trein, een _niet bediende_ bushalte, een _gehistoreerd_ adres, etc.
 2. Je domeinmodel beschrijft een changeset. In dat geval beschrijf je de delete in je specifiek domeinmodel. Zie bijvoorbeeld https://www.eventnotifications.net/#activities

Alle concepten zijn aanwezig om deze cases te ondersteunen zonder aanpassingen aan de spec en deze issue mag gesloten worden.
