### ISSUE TITLE
Definitie SHAPE 

### ISSUE THREAD

**Issue by bertvannuffelen** [Informatievlaanderen/OSLOthema-ldes#5]
Issue gepost als https://github.com/Informatievlaanderen/OSLO-Discussion/issues/407

Issues in deze repository dienen inhoudelijke en semantische issues met betrekking tot de verschillende OSLO domeinmodellen aan te kaarten. Om technische (broken links, verkeerde mapping van termen op URI's...) of editoriale (typo's, fouten in de HTML weergave...) problemen aan te kaarten verwijzen we naar de [Data.Vlaanderen.be repository](https://github.com/Informatievlaanderen/Data.Vlaanderen.be/issues).

Model(len) waarop de issue van toepassing is:

Omschrijving van het probleem:
De definite van shape zegt: 'Een shape wordt opgelegd aan alle elementen van de LDES. Voorbeelden van zo'n shape zijn SHACL en ShEx. De shape moet cohorent zijn doorheen heel de Linked Data Event Stream

Daarmee zegt de definitie nog niet wat een shape net is - bv. dat het de properties beschrijft van de concepts of elements of data types...of zoiets
Omschrijving van een mogelijke oplossing:

**Comment by ArneVanDerStuyft** [comment]
Dag Bert, 

Bedankt voor de terechte opmerking. 

Zoals aangehaald in het afsluitend webinar van OSLO LDES op 25/11 werd de definitie gewijzigd naar 'Een shape is een technische beschrijving van de structuur waaraan de objecten uit de LDES moeten voldoen. ​'

Deze definitie werd door het ecosysteem aanvaard.
