### ISSUE TITLE
Naamgevingen Engels vs Nederlands

### ISSUE THREAD

**Issue by davidvlaminck** [Informatievlaanderen/OSLOthema-ldes#6]
Ik merk dat in de naamgevingen van de klassen, attributen en types dikwijls Nederlands en Engels door elkaar gebruikt wordt.
Het is consistenter om dit allemaal in dezelfde taal te doen en dan nog het liefst in het Engels. Ook al wordt hier gewerkt aan een Vlaamse standaard, er zullen ook niet-Nederlandstaligen werken met deze standaard. Bovendien zijn er voor sommige termen geen goed Nederlands alternatief waardoor je toch telkens moet teruggrijpen naar het Engels.
Je kan dus beter alle termen in het Engels zetten en waar nodig de mogelijkheid voorzien om waardes in meerdere talen te laten invullen.

**Comment by ArneVanDerStuyft** [comment]
Dag David, 

Bedankt voor uw opmerking. Dit vraagstuk werd plenair besproken gedurende de derde thematische werkgroep (zie ook het  verslag [OSLO LDES - Derde thematische werkgroep](https://github.com/Informatievlaanderen/OSLOthema-ldes/raw/standaardenregister/reports/Verslag%20thematische%20werkgroep%203%20-%2017%20maart%202022.docx)). Samen met de deelnemers is er toen afgesproken om in het datamodel zowel met Nederlandstalige als Engelstalige begrippen te werken. Dit komt voort uit het feit dat binnen OSLO Engelstalige termen enkel zijn toegestaan wanneer het om technische documentatie of begrippen gaat. Gedurende de implementatie mag men uiteraard wel met Engelstalige termen werken. 

Hopelijk biedt dit een antwoord op uw opmerking.
